authors:
  porosdata:
    name: PorosData Team
    description: Project maintainers
    avatar: assets/images/author-avatar-default.svg
    url: https://github.com/KiventYip/PorosData-doc
  jianhonng:
    name: Jianhonng
    description: PorosData maintainer and technical writing
    avatar: assets/images/author-avatar-default.svg
    url: https://github.com/KiventYip
